# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  book-a-private:
    container_name: book-a-private
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    # ENV_VARIABLE: ${ENV_VARIABLE}
    # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    volumes:
      # no src in Dockerfile, only via mount
      # must see src changes, frontend build prod
      # to avoid rebuilding container on src change
      - ./:/app
      - book-a-private-node_modules:/app/node_modules
      - book-a-private-next:/app/.next
      - book-a-private-dist:/app/dist
    env_file:
      - ./.env.test
    depends_on:
      - db
    networks:
      - internal-test
    # Add more containers below (nginx, postgres, etc.)
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    networks:
      - internal-test
      - external-host

volumes:
  book-a-private-node_modules:
  book-a-private-next:
  book-a-private-dist:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  internal-test:
    external: false
  # for adminer dev d-c
  external-host:
    external: true
