name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install dependancies
      run: npm install
   
    - name: Build the Docker image
      run: npm run test
