name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate Prisma client
      run: npx prisma generate

    - name: Migrate db schema
      run: npx prisma migrate deploy
   
    - name: Build the Docker image
      run: npm run test
