name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://prisma:prisma@localhost:5433/tests

    services:
      postgres:
        image: postgres:13
      env:
        POSTGRES_USER: prisma
        POSTGRES_PASSWORD: prisma
        POSTGRES_DB: tests
      ports:
        - 5433:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Migrate db schema
        run: npx prisma migrate deploy

        # integrated controllers with services
      - name: Run server integration tests
        run: npm test:server:integration
